### ISSUE TITLE
Commit message

### ISSUE THREAD

**Issue by aascedu** [Stafpecc/ft_printf#1]
Hello,

je suis desole de faire une issue pour un printf, juste je vois que tu aimes bien le DevOps, t'as mis des tests sur ta CI c'est sympa, bonne pratique devops.
Mais les noms de commit serieux, la ca va c'est printf, courage quand t'aurais push un truc qui fallait pas sur minishell ou des gros projets ! Prends l'habitude de faire des commit qui suivent une norme, c'est un truc qui coute rien et niveau pratique devops, c'est le minimum quoi.
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
Enjoy !

**Comment by Stafpecc** [comment]
Merci beaucoup pour l'attention ! Je ferais plus attentions aux noms de mes commits, je n'y avais pas reelement fait attention et je t'en remercie de m'avoir partager ça
Si jamais il y a d'autre chose hesite pas je suis ouvert
